kind: Deployment
apiVersion: apps/v1
metadata:
  name: raven
spec:
  replicas: 1
  selector:
    matchLabels:
      app: raven
  template:
    metadata:
      labels:
        app: raven
    spec:
      containers:
      - name: raven-container
        image: neoreeps/raven
        command: ["/home/raven/start.sh"]
        args: ["-conf=/home/raven/.raven/raven.conf",
               "-datadir=/raven-data",
               "-addnode=165.232.129.128",
               "-addnode=76.103.93.14",
               "-addnode=71.202.82.78",
               "-addnode=159.65.98.117",
               "-addnode=104.6.159.124",
               "-addnode=73.48.154.249",
               "-addnode=24.10.21.208"]
        volumeMounts:
          - name: raven-data
            mountPath: /raven-data
      volumes:
        - name: raven-data
          hostPath:
            path: /data/raven-data
            type: Directory
      nodeSelector:
        hw: rpi4
---
apiVersion: v1
kind: Service
metadata:
  name: raven-service
spec:
  ports:
  - name: default
    targetPort: 8767 
    port: 8767
  selector:
    app: raven
---
#apiVersion: extensions/v1beta1
#kind: Ingress
#metadata:
#  name: raven-ingress
#  annotations:
#    kubernetes.io/ingress.class: traefik
#spec:
#  rules:
#  - host: raven.reeps.io
#    http:
#      paths:
#      - path: /
#        backend:
#          serviceName: raven-service
#          servicePort: default
