apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-conf
  namespace: kube-system
data:
  traefik.toml: |
    defaultEntryPoints = ["http","https","raven"]
    debug = false
    logLevel = "INFO"

    # Do not verify backend certificates (use https backends)
    #InsecureSkipVerify = true
    [entryPoints]
      [entryPoints.http]
      address = ":80"
      compress = true
        #[entryPoints.http.redirect]
        #  entryPoint = "https"
      [entryPoints.https]
      address = ":443"
      compress = true
        [entryPoints.https.tls]
         minVersion = "VersionTLS12"
        cipherSuites = [
          "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
          "TLS_RSA_WITH_AES_256_GCM_SHA384"
         ]

    [kubernetes]

    [ping]
    entryPoint = "http"

    # some documentation
    # https://docs.traefik.io/v1.7/configuration/acme/

    # Let's encrypt configuration
    [acme]
    email = "kenny@reeps.io"
    # /acme is volume mount from /data on all nodes
    storage = "/acme/acme.json"
    entryPoint = "https"
    acmeLogging = true
    #onDemand = true # DEPRECATED - create certificate on first access
    onHostRule = true  # true for non-wildcard
    # Use a HTTP-01 acme challenge rather than TLS-SNI-01 challenge
    [acme.httpChallenge]
    entryPoint = "http"
