apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-conf
  namespace: kube-system
data:
  traefik.toml: |
    defaultEntryPoints = ["http","https"]
    debug = false
    logLevel = "INFO"

    # Do not verify backend certificates (use https backends)
    #InsecureSkipVerify = true
    [entryPoints]
      [entryPoints.http]
      address = ":80"
      compress = true
        [entryPoints.http.redirect]
        entryPoint = "https"
      [entryPoints.https]
      address = ":443"
      compress = true
        [entryPoints.https.tls]
         minVersion = "VersionTLS12"
        cipherSuites = [
          "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
          "TLS_RSA_WITH_AES_256_GCM_SHA384"
         ]

    [kubernetes]

    [ping]
    entryPoint = "http"

    #[etcd]
    #endpoint = ":2379"
    ## Enable watch Etcd changes.
    #watch = true
    ## Prefix used for KV store.
    #prefix = "/traefik"
    ## Force to use API V3 (otherwise still use API V2)
    #useAPIV3 = true

    # https://docs.traefik.io/v1.7/configuration/acme/

    # Let's encrypt configuration
    [acme]
    email = "kenny@reeps.io"
    #storage = "traefik/acme/account" # key/value store
    storage = "/acme/acme.json"
    entryPoint = "https"
    acmeLogging = true
    #onDemand = true # DEPRECATED - create certificate on first access
    onHostRule = true  # true for non-wildcard
    # Use a HTTP-01 acme challenge rather than TLS-SNI-01 challenge
    [acme.httpChallenge]
    entryPoint = "http"

    #[[acme.domains]]
    #main = "*.reeps.io"
    #sans = ["reeps.io", "whoami.reeps.io", "whoareyou.reeps.io", "home.reeps.io"]
